// @ts-check
import confusingBrowserGlobals from "confusing-browser-globals";

const restrictedBrowserGlobals = [
  { name: "isFinite", message: "Use Number.isFinite instead" },
  { name: "isNaN", message: "Use Number.isNaN instead" },
  ...confusingBrowserGlobals.map((name) => ({
    name,
    message: `Use window.${name} instead`,
  })),
];

/** @type {import("oxlint").OxlintConfig["rules"]} */
const rules = {
  "array-callback-return": ["error", { allowImplicit: true }],
  eqeqeq: ["error", "always", { null: "ignore" }],
  "new-cap": [
    "error",
    {
      newIsCap: true,
      newIsCapExceptions: [],
      capIsNew: false,
      capIsNewExceptions: ["Immutable.Map", "Immutable.Set", "Immutable.List"],
    },
  ],
  "no-param-reassign": [
    "error",
    {
      props: true,
      ignorePropertyModificationsFor: [
        "prev",
        "acc",
        "accumulator",
        "e",
        "ctx",
        "context",
        "req",
        "request",
        "res",
        "response",
        "$scope",
        "staticContext",
        "sharedState",
        "state",
      ],
    },
  ],
  "no-restricted-globals": ["error", ...restrictedBrowserGlobals],
  "no-restricted-exports": [
    "error",
    {
      restrictedNamedExports: ["default", "then"],
    },
  ],
  "no-return-assign": ["error", "always"],
  "object-shorthand": ["error", "always", { ignoreConstructors: false, avoidQuotes: true }],
  "prefer-const": ["error", { destructuring: "any", ignoreReadBeforeAssign: true }],
  "prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
  "unicode-bom": ["error", "never"],

  "default-case": ["error", { commentPattern: "^no default$" }],
  "default-case-last": "error",
  "default-param-last": "error",
  "func-names": "warn",
  "no-console": "warn",
  "no-alert": "error",
  "no-array-constructor": "error",
  "no-await-in-loop": "error",
  "no-constructor-return": "error",
  "no-eval": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-implied-eval": "error",
  "no-inner-declarations": "error",
  "no-labels": "error",
  "no-lone-blocks": "error",
  "no-lonely-if": "error",
  "no-loop-func": "error",
  "no-multi-assign": "error",
  "no-nested-ternary": "error",
  "no-new-func": "error",
  "no-object-constructor": "error",
  "no-promise-executor-return": "error",
  "no-proto": "error",
  "no-redeclare": "error",
  "no-script-url": "error",
  "no-self-compare": "error",
  "no-sequences": "error",
  "no-shadow": "error",
  "no-template-curly-in-string": "error",
  "no-throw-literal": "error",
  "no-unmodified-loop-condition": "error",
  "no-useless-call": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "error",
  "no-useless-constructor": "error",
  "no-useless-return": "error",
  "no-var": "error",
  "operator-assignment": ["error", "always"],
  "prefer-exponentiation-operator": "error",
  "prefer-numeric-literals": "error",
  "prefer-object-has-own": "error",
  "prefer-object-spread": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  radix: "error",
  "symbol-description": "error",
  yoda: "error",

  "import/extensions": [
    "error",
    "ignorePackages",
    {
      js: "never",
      cjs: "never",
      mjs: "never",
      jsx: "never",
      ts: "never",
      cts: "never",
      mts: "never",
      tsx: "never",
    },
  ],
  "import/no-amd": "error",
  "import/no-cycle": ["error", { ignoreExternal: true }],
  "import/no-duplicates": "error",
  "import/no-dynamic-require": "warn",
  "import/no-empty-named-blocks": "off",
  "import/no-mutable-exports": "error",
  "import/no-named-default": "error",
  "import/no-unassigned-import": "error",
  "import/no-webpack-loader-syntax": "error",

  "typescript/consistent-type-exports": "error",
  "typescript/consistent-type-imports": "error",
  "typescript/default-param-last": "error",
  "typescript/no-deprecated": "warn",
  "typescript/no-confusing-void-expression": "error",
  "typescript/no-dynamic-delete": "error",
  "typescript/no-explicit-any": "error",
  "typescript/no-floating-promises": "error",
  "typescript/no-import-type-side-effects": "error",
  "typescript/no-invalid-void-type": "error",
  "typescript/no-loop-func": "error",
  "typescript/no-misused-promises": ["error", { checksConditionals: false }],
  "typescript/no-mixed-enums": "error",
  "typescript/no-non-null-asserted-nullish-coalescing": "error",
  "typescript/no-non-null-assertion": "error",
  "typescript/no-redeclare": "error",
  "typescript/no-shadow": "error",
  "typescript/no-unnecessary-condition": "error",
  "typescript/no-unnecessary-qualifier": "error",
  "typescript/no-unsafe-argument": "error",
  "typescript/no-unsafe-assignment": "error",
  "typescript/no-unsafe-call": "error",
  "typescript/no-unsafe-member-access": "error",
  "typescript/no-unsafe-return": "error",
  "typescript/no-useless-constructor": "error",
  "typescript/no-empty-object-type": "error",
  "typescript/prefer-enum-initializers": "error",
  "typescript/prefer-literal-enum-member": "error",
  "typescript/prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
  "typescript/prefer-reduce-type-parameter": "error",
  "typescript/prefer-return-this-type": "error",
  "typescript/switch-exhaustiveness-check": "error",
  "typescript/unified-signatures": "error",
  "typescript/use-unknown-in-catch-callback-variable": "error",

  "unicorn/consistent-function-scoping": "off",
  "unicorn/no-array-sort": "error",
  "unicorn/no-useless-fallback-in-spread": "error",
  "unicorn/require-module-specifiers": "off",
};

export default rules;
