name: "CI"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "main"

jobs:
  skip-check:
    if: ${{ !contains(github.event.pull_request.title, 'chore(release):') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "run only on non-release commits"

  validate:
    needs: [skip-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 ## Needed for Changesets to find `main` branch
      ## https://github.com/changesets/changesets/issues/517
      - name: Create git reference to main branch (for Changesets)
        if: ${{ github.event.pull_request.title != 'Version Packages' }}
        run: git pull --force --no-tags origin main:main
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Check Changeset Status
        run: pnpm exec changeset status --since=main
      - name: Check Format
        run: pnpm format:check
      - name: Check Lint
        run: pnpm lint
      - name: Run Tests
        run: pnpm test
